version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mattermost_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - matternet

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost_app
    restart: unless-stopped
    environment:
      MM_CONFIG: config/config.json
      DB_HOST: db
      DB_PORT: 5432
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10
      MM_SERVICESETTINGS_SITEURL: https://${DOMAIN}
      MM_PLUGINSETTINGS_ENABLE: "false"
    volumes:
      - ./data/mattermost:/mattermost/data
    depends_on:
      - db
    networks:
      - matternet
    ports:
      - "8065:8065"  # теперь порт доступен снаружи хоста

networks:
  matternet:
    driver: bridge